# This is a basic workflow to help you get started with Actions

name: Editorconfig

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - '**'      # matches every branch
    - '!master' # We want to exclude master, because this will forcefully push changes, we don't want to forcefully push to master.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1.4.3
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: npm install
        run: npm i
      - name: add .dotnet/tools to path
        run: echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
      - run: dotnet tool install -g dotnet-format
      - run: dotnet format --folder ${ github.workspace }
      - name: Add Zip Files to Commit and push
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
            echo 'no changes to analyze'
          else 
            git config user.name osobeso
            git config user.email osobeso@github.com
            git add .
            git commit -m "dotnet format applied."
            git push
          fi
